services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_URL=postgres://user:password@postgres:5432/dbname
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:15.8  
    container_name: postgres15.8  
    restart: always
    environment:       
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}          
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data: 
